export const carJsonData = [
  {
    id: 1,
    name: "Toyota Camry",
    description: "A reliable and efficient sedan.",
    year: 2023,
    model: "Camry SE",
    type: "brand new",
    price: 25000,
    quantity: 10,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 2,
    name: "Honda Civic",
    description: "A popular compact car with great fuel economy.",
    year: 2022,
    model: "Civic LX",
    type: "brand new",
    price: 22000,
    quantity: 15,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 3,
    name: "Ford Mustang",
    description: "An iconic sports car with powerful performance.",
    year: 2021,
    model: "Mustang GT",
    type: "2nd hand",
    price: 30000,
    quantity: 5,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 4,
    name: "Chevrolet Tahoe",
    description: "A large SUV with ample space and strong towing capacity.",
    year: 2020,
    model: "Tahoe LT",
    type: "2nd hand",
    price: 35000,
    quantity: 8,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 5,
    name: "Nissan Altima",
    description: "A midsize sedan with advanced safety features.",
    year: 2023,
    model: "Altima SV",
    type: "brand new",
    price: 24000,
    quantity: 12,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 6,
    name: "BMW X5",
    description: "A luxury SUV with top-notch amenities and performance.",
    year: 2019,
    model: "X5 xDrive40i",
    type: "2nd hand",
    price: 40000,
    quantity: 6,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 7,
    name: "Audi A4",
    description: "A premium sedan with a sleek design and advanced technology.",
    year: 2021,
    model: "A4 Premium",
    type: "2nd hand",
    price: 32000,
    quantity: 9,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 8,
    name: "Mercedes-Benz C-Class",
    description:
      "A luxury compact car with a smooth ride and elegant interior.",
    year: 2022,
    model: "C300",
    type: "brand new",
    price: 42000,
    quantity: 7,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 9,
    name: "Tesla Model 3",
    description: "A high-tech electric vehicle with impressive range.",
    year: 2023,
    model: "Model 3 Standard Range Plus",
    type: "brand new",
    price: 45000,
    quantity: 10,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 10,
    name: "Hyundai Sonata",
    description:
      "A stylish sedan with a comfortable interior and good fuel efficiency.",
    year: 2021,
    model: "Sonata SEL",
    type: "2nd hand",
    price: 20000,
    quantity: 13,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 11,
    name: "Kia Sorento",
    description: "A midsize SUV with a spacious cabin and modern features.",
    year: 2020,
    model: "Sorento EX",
    type: "2nd hand",
    price: 27000,
    quantity: 11,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 12,
    name: "Mazda CX-5",
    description: "A compact SUV with sporty handling and a premium interior.",
    year: 2023,
    model: "CX-5 Touring",
    type: "brand new",
    price: 26000,
    quantity: 14,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 13,
    name: "Subaru Outback",
    description: "A rugged crossover with standard all-wheel drive.",
    year: 2022,
    model: "Outback Premium",
    type: "brand new",
    price: 28000,
    quantity: 10,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 14,
    name: "Volkswagen Golf",
    description: "A fun-to-drive hatchback with a high-quality interior.",
    year: 2021,
    model: "Golf TSI",
    type: "2nd hand",
    price: 21000,
    quantity: 9,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 15,
    name: "Volvo XC90",
    description:
      "A luxury SUV with advanced safety features and a comfortable ride.",
    year: 2019,
    model: "XC90 T6 Momentum",
    type: "2nd hand",
    price: 45000,
    quantity: 5,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 16,
    name: "Lexus RX 350",
    description:
      "A premium midsize SUV with a smooth ride and upscale interior.",
    year: 2020,
    model: "RX 350",
    type: "2nd hand",
    price: 38000,
    quantity: 6,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 17,
    name: "Jeep Wrangler",
    description: "A rugged SUV with excellent off-road capabilities.",
    year: 2023,
    model: "Wrangler Sport",
    type: "brand new",
    price: 35000,
    quantity: 12,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 18,
    name: "Chevrolet Silverado",
    description: "A full-size pickup truck with strong towing capacity.",
    year: 2021,
    model: "Silverado 1500 LT",
    type: "2nd hand",
    price: 34000,
    quantity: 7,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 19,
    name: "Porsche 911",
    description: "A high-performance sports car with an iconic design.",
    year: 2020,
    model: "911 Carrera",
    type: "2nd hand",
    price: 90000,
    quantity: 3,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
  {
    id: 20,
    name: "Range Rover Evoque",
    description:
      "A luxury compact SUV with a stylish design and off-road capability.",
    year: 2022,
    model: "Evoque S",
    type: "brand new",
    price: 50000,
    quantity: 8,
    imageUrl:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2025/civic-sedan/non-VLP/04-Nav/MY25_Civic_Sedan_Petrol_All_Vehicles_Jelly.png?sc_lang=en&hash=25C6D3C1A7EDC2871B851B9F7DDFA13C",
  },
];
